name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
        working-directory: ./src
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ../github/requirements.txt

    - name: Build
      run: pyinstaller --noconfirm --onefile --noconsole --name "WebModpack" --add-data "web\\;.\\web" --add-data "mods\\;.\\mods" main.py

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Web Modpack
        path: ./src/dist/Web Modpack.exe
